title: lauren-steve-2017
email: hello@dadler.codes
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.opstad-oates-2017.com" # the base hostname & protocol for your site
twitter_username: adlerography
github_username: danieladler

# Build settings
markdown: kramdown
theme: minima
